### PR TITLE
Let expressions

### LINKED ISSUE #93: unexpected sort "bvand"
We don't parse bvand

test benchmark: 
https://github.com/SyGuS-Org/benchmarks/blob/master/comp/2018/General_Track/btr-am-base-index-scale-disp-solution-0.sl

### LINKED ISSUE #96: parsing let expressions
Let expression parsing errors:
example benchmark:
https://github.com/SyGuS-Org/benchmarks/blob/master/lib/Inv_Track/andrew_lustre/FIREFLY_5.lus.sl
~~~
12: unexpected sort: `let'
~~~

### PR DESCRIPTION
**Pull request by pkesseli**
Support `let` with implicit and explicit types. The latter is actually not part of the SyGuS Language Standard 2.0 as far as I can tell (https://sygus.org/assets/pdf/SyGuS-IF_2.0.pdf), but some of the benchmarks use this feature. Closes #93, closes #96.

### CODE REVIEW

**Comment by polgreen** [comment]
I think SyGuS 2.0 supports let expressions in exactly the same format as SMTlib. SyGuS 1.0 required explicit types. 

> Previously, a let-term was written(let((x T t))...)where T indicates the type oft. Now, it must be written in the SMT-LIB compliant way(let((x t))...).

We can choose to only support SyGuS 2.0 or be nice and support both. I don't have a view either way, but worth noting that CVC4 no longer supports SyGuS 1.0 at all. 

Also, i created a conflict, sorry, should have merged these in a different order.

**Comment by polgreen** [comment]
Also, at some point we should try to merge the PR for a new SyGuS parser that i made ages ago, which is built on top of the SMTlib parser in CBMC. But maybe now is not the time

**Comment by pkesseli** [comment]
> I think SyGuS 2.0 supports let expressions in exactly the same format as SMTlib. SyGuS 1.0 required explicit types.
> 
> > Previously, a let-term was written(let((x T t))...)where T indicates the type oft. Now, it must be written in the SMT-LIB compliant way(let((x t))...).
> 
> We can choose to only support SyGuS 2.0 or be nice and support both. I don't have a view either way, but worth noting that CVC4 no longer supports SyGuS 1.0 at all.
> 
> Also, i created a conflict, sorry, should have merged these in a different order.

That makes sense, as you may notice in the PR one token lookahead is not enough to distinguish the two production rules. The current `let_expression` implementation tries SyGuS 2.0 format, i.e. implicit types, and falls back to SyGuS 1.0 if that fails. I think it's safe to keep it this way for now.

**Comment by pkesseli** [comment]
> Also, at some point we should try to merge the PR for a new SyGuS parser that i made ages ago, which is built on top of the SMTlib parser in CBMC. But maybe now is not the time

Yes, I noticed that PR. I assume my changes caused a few conflicts, so we should probably revive that one (and CI) after the journal submission.

**Review by polgreen — APPROVED** [review]

**Pull request merged**
